config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :friendships, only: [:index, :new, :create, :destroy]

  resources :expense_groups do
    member do
      get 'add_friends'
      post 'create_membership'
      delete 'remove_friend'
    end
    resources :expenses, only: [:index, :new, :create, :destroy]
  end

  root 'expense_groups#index'
end

app/models/expense_group.rb
# expense_group model
class ExpenseGroup < ApplicationRecord
  validates :name, presence: true
  validates :user_id, presence: true

  has_and_belongs_to_many :users
  has_many :expenses
end

app/controllers/expense_groups_controller.rb
# expense group controller
class ExpenseGroupsController < ApplicationController
  before_action :set_expense_group, only: [:show, :destroy, :add_friends, :remove_friend, :create_membership]

  def index
    @expense_groups = current_user.expense_group
  end

  def new
    @expense_group = ExpenseGroup.new
  end

  def create
    @expense_group = ExpenseGroup.new(expense_group_params)
    @expense_group.created_by = current_user.email

    if @expense_group.save
      @expense_group.users << current_user
      flash[:notice] = "Expense group created successfully."
      redirect_to expense_groups_path
    else
      render 'new'
    end
  end

  def destroy
    if @expense_group.destroy
      flash[:notice] = "Expense group deleted successfully."
    else
      flash[:alert] = "Failed to delete the expense group."
    end

    redirect_to expense_groups_path
  end

  def show
    @expenses = @expense_group.expenses
    @user_balances = calculate_user_balances(@expense_group)
  end

  def calculate_user_balances(expense_group)
    total_amount_paid = Expense.where(expense_group:).sum(:amount)
    total_users = @expense_group.users.count
    equal_share = total_amount_paid / total_users

    user_balances = {}

    @expense_group.users.each do |user|
      user_expenses = Expense.where(expense_group:, user:).sum(:amount)
      user_balance = (equal_share - user_expenses).round(2)
      user_balances[user] = user_balance
    end

    user_balances[:total_amount_paid] = total_amount_paid
    user_balances[:equal_share] = equal_share.round(2)

    user_balances
  end

  def add_friends
    @friends = current_user.friends
  end

  def create_membership
    @user = User.find(params[:user_id])

    if @expense_group.users.include?(@user)
      flash[:alert] = "User is already in the group."
    else
      @expense_group.users << @user
      flash[:notice] = "User added to the group."
    end

    redirect_to expense_group_path(@expense_group)
  end

  def remove_friend
    @user = User.find(params[:user_id])

    if @expense_group.users.include?(@user)
      @expense_group.users.delete(@user)
      flash[:notice] = "User removed from the group."
    else
      flash[:alert] = "User is not in the group."
    end

    redirect_to expense_group_path(@expense_group)
  end

  private

  def set_expense_group
    @expense_group = ExpenseGroup.find(params[:id])
  end

  def expense_group_params
    params.require(:expense_group).permit(:name)
  end
end

app/helpers/expense_group_helper.rb
module ExpenseGroupHelper # rubocop:disable Style/Documentation
end

app/helpers/expense_groups_helper.rb
module ExpenseGroupsHelper # rubocop:disable Style/Documentation
end

app/views/expense_groups/add_friends.html.erb
<h1>Add member to group </h1>

<%= form_with(url: create_membership_expense_group_path(@expense_group), method: :post) do |form| %>
  <div>
    <%= form.label :user_id, "Select Friend to Add" %>
    <%= form.collection_select(:user_id, @friends, :id, :email, { prompt: "Select a friend" }, { required: true }) %>
  </div>

  <div>
    <%= form.submit "Add Friend" %>
  </div>
<% end %>

app/views/expense_groups/index.html.erb
<h1>Dashboard</h1>

<%= button_to "Create Group" , new_expense_group_path, method: :get%>
<%= button_to "Friends" , friendships_path, method: :get%>
<%= button_to "Sign Out", destroy_user_session_path, method: :delete%>


<h1>Your Expense Groups</h1>

<% if @expense_groups.any? %>
  <ul>
    <% @expense_groups.each do |expense_group| %>
      <li>
        <%= link_to expense_group.name, expense_group %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>You are not a member of any expense groups.</p>
<% end %>

app/views/expense_groups/new.html.erb
<h1>Create Expense Group</h1>

<%= form_with(model: @expense_group, url: expense_groups_path, method: :post) do |form| %>

  <div>
    <%= form.label :name, "Group Name" %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.submit "Create Group" %>
  </div>
<% end %>

app/views/expense_groups/show.html.erb
<h1><%= @expense_group.name %></h1>

<% if @expense_group.created_by == current_user.email %>
  <%= button_to "Add Members", add_friends_expense_group_path(@expense_group), method: :get %>
  <%= button_to "Delete Group", @expense_group, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<% end %>


<h2>Members in this Group:</h2>
<ul>
  <% @expense_group.users.each do |friend| %>
    <li>
      <%= friend.email %>

      <% if friend == current_user %>
      <% elsif @expense_group.created_by == current_user.email %>
        <%= button_to "Remove", remove_friend_expense_group_path(@expense_group, user_id: friend.id), method: :delete %>
      <% end %>
      
    </li>
  <% end %>
</ul>


<h2>Expenses:</h2>
<ul>
  <% @expense_group.expenses.each do |expense| %>
    <li>
      Amount : <%= expense.amount %>, Paid by : <%= expense.user.email %>
      <% if @expense_group.created_by == current_user.email %>
        <%= button_to "Delete", expense_group_expense_path(@expense_group, expense), method: :delete%>
      <% end %>
    </li>
  <% end %>
</ul>

<h2>User Balances:</h2>
<ul>
  <% @user_balances.each do |user, balance| %>
    <% if user.is_a?(User) %>
      <li> <%= user.email %> owes :  <%= balance %> in total </li>
    <% else %>
      <strong><%= user %>:</strong> <%= balance%> , 
    <% end %>
  <% end %>
</ul>

<% if @expense_group.created_by == current_user.email %>
  <%= link_to "Add Expense", new_expense_group_expense_path(@expense_group) %>
<% end %>