config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :friendships, only: [:index, :new, :create, :destroy]

  resources :expense_groups do
    member do
      get 'add_friends'
      post 'create_membership'
      delete 'remove_friend'
    end
    resources :expenses, only: [:index, :new, :create, :destroy]
  end

  root 'expense_groups#index'
end

app/models/friendship.rb
# friendship model
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/controllers/friendships_controller.rb
# friendship controller
class FriendshipsController < ApplicationController

  def index
    @user = current_user
    @friendship = @user.friends
  end

  def new
    @friendship = Friendship.new
  end

  def create
    email = params[:friendship][:email]
    friend = User.find_by(email: email)
  
    if friend
      if current_user == friend
        flash[:alert] = "You cannot add yourself as a friend."

      elsif current_user.friends.include?(friend)
        flash[:alert] = "Already your friend."
      else
        Friendship.create(user: current_user, friend: friend)
        Friendship.create(user: friend, friend: current_user)
        flash[:notice] = "Friend added"
      end
    else
      flash[:alert] = "User not found."
    end
  
    redirect_to friendships_path
  end

  def destroy
    friend_id = params[:id]
    friendship = Friendship.find_by(friend_id: friend_id, user_id: current_user.id)
    reverse_friendship = Friendship.find_by(friend_id: current_user.id, user_id: friend_id)

    if friendship
      friendship.destroy
      reverse_friendship.destroy
      flash[:notice] = "Friendship destroyed"

    else
      flash[:alert] = "Friendship not found"
    end

    redirect_to friendships_path
  end

  private

  def set_friendship
    @friendship = Friendship.find(params[:id])
  end

  def friendship_params
    params.require(:friendship).permit(:email)
  end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<h1>List of friends</h1>
<%= button_to 'Add new friend' , new_friendship_path, method: :get%>
<% if @friendship.any? %>
  <ul>
    <% @friendship.each do |friend| %>
      <li><%= friend.email %></li>
      <%= button_to 'Remove Friend', friendship_path(friend), method: :delete %>
    <% end %>
  </ul>
<% else %>
  <p>You don't have any friend</p>
<% end %>

app/views/friendships/new.html.erb
<h1>Add a Friend</h1>

<%= form_with(model: Friendship.new, url: friendships_path, method: :post) do |form| %>
  <%= form.label :email, "Enter Friend Email" %>
  <%= form.text_field :email, required: true%>
  <%= form.submit "Add Friend" %>
<% end %>