config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :friendships, only: [:index, :new, :create, :destroy]

  resources :expense_groups do
    member do
      get 'add_friends'
      post 'create_membership'
      delete 'remove_friend'
    end
    resources :expenses, only: [:index, :new, :create, :destroy]
  end

  root 'expense_groups#index'
end

app/controllers/expenses_controller.rb
# expense controller
class ExpensesController < ApplicationController
  before_action :set_expense_group_and_expense, only: [:index, :new, :create, :edit, :show, :update, :destroy]

  def index
    @expenses = @expense_group.expenses
  end

  def new
    @expense = @expense_group.expenses.build
  end

  def create
    @expense = @expense_group.expenses.build(expense_params)

    if @expense.save
      flash[:notice] = "Expense added successfully."
      redirect_to expense_group_path(@expense_group)
    else
      render 'new'
    end
  end

  def destroy
    @expense.destroy
    flash[:notice] = "Expense deleted successfully."
    redirect_to expense_group_path(@expense_group)
  end

  private

  def set_expense_group_and_expense
    @expense_group = ExpenseGroup.find(params[:expense_group_id])
    @expense = @expense_group.expenses.find(params[:id]) if params[:id]
  end

  def expense_params
    params.require(:expense).permit(:description, :amount, :user_id)
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper # rubocop:disable Style/Documentation
end

app/views/expenses/new.html.erb
<h1>Add Expense to <%= @expense_group.name %></h1>

<%= form_with(model: [@expense_group, @expense], url: expense_group_expenses_path(@expense_group, @expense), method: :post) do |form| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% @expense.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description, required: true %>
  </div>

  <div>
    <%= form.label :amount %>
    <%= form.text_field :amount, required: true %>
  </div>

  <div>
    <%= form.label :user_id, "Select User" %>
    <%= form.collection_select(:user_id, @expense_group.users, :id, :email, { prompt: "Select a user" }, { required: true }) %>
  </div>

  <div>
    <%= form.submit 'Create Expense' %>
  </div>
<% end %>


<%= link_to 'Back', expense_group_expenses_path(@expense_group) %>